### ISSUE TITLE
How do you define the role of Front End Devops developer?

### ISSUE THREAD

**Issue by fraserxu** [gaearon/ama#103]
Hi @gaearon , I want to further a discussion with you back to January about the definition of Front End Devops.

> The real fatigue: developers doing front-end devops instead of working on their apps. Frustrating for everyone. Backend devs solved this.
> 
> Otherwise it’s time we agree “front-end devops” is a thing and treat it seriously as an activity dedicated people do.

First a little background about the question: I joined a new company 3 month ago, our website has 150 million Page Views a month, it's also one of the largest creative market in the world.

But it's also very "old". It has about 10 years of history, and the Front End part of the app is build on top of a Rails backend, and server rendered page. 

It's using [Sprocket](https://github.com/rails/sprockets-rails) to bundle jQuery code written in CoffeeScript, bower for package management. For lots of reason we want to free our Front End code from blocking by the Back End code. And we are trying to bring in Webpack(assets management) and Babel + a little React(if make sense), and NPM for package management to replace the existing stack.

We are dealing with a rather monolithic code base(it's quite common in Rails world I believe), so the work  I need to do it's much more complicated(and it also needs to be super secure as there's a business running on top of it). 

Me personally had used the new stack in a few project, and it's not a lot of work to apply it to a new project as well. But the code base I'm dealing with now it's totaly different, here's a few challenge I need to fix while doing it:
- **Keep the existing code running, and try to not break other people's workflow** both front-end and back-end
- **Progressive enhancement** old browser, javascript disabled by user, packages not on npm...
- **Test everything** unit test, browser test, end to end test...
- **Prepare build environment** node version management, aws permissions, npm cache..., on both local server, CI server, staging server, and production server(we have a traditional Rails stack, so Node.js is a relatively new thing for us)
- **Document everything** as we're introducing Babel in, we need to teach Back End developers(for rails developers they like CoffeeScript) the new syntax, the workflow, how npm works, how to write test
- **Build a better Front End culture** it's a rather important task to do if we want to introduce the new stack, as that explains how the ecosystem works
- **How to do open source** this maybe part of the Front End culture?

This could be a longer list as some of them can be trivial(webpack config management for example) but could serve as a basement for the role.

Above it's a list of technical issues I think need to solve as a **Front End Devops Developer**, there are a few prerequisites for this role to be exist as well:
- You need to have a **certain scale of project size** to be able to have a dedicate person to work on that full time
- Your project or business needs to be running for **at least 3 or 4 years** so the time spend on this is worth investment 
- You have a **heavy enough Front End code base** to make sure you have enough job to do

**Side note:** I list all the requirements here because I'm at a stage that I need to convince my manager the importance of this role, first they don't have a good understanding of the current Front End ecosystem(as most of them are Rails developers), secondly this is a **new role** and does not exist on any open roles in a company.

The role is a quite big but also interesting challenge for me, and I'm willing to take that as a full-time job. But the reality **challenges** are: 
- as a normal Front End developer, you have your daily app development work to do, it can be hard to work on them at the same time
- Even though you might be able to allocated sometime on it, you will leave an expression to other team members that you are not doing anything as it's out the scope of the team
- As a new member of the team, you haven't gained enough trust to be able to do so
- Other people does not care about your work and your work is not being appreciate, or even worst, **you are making their life harder**.
- You are working with a group of traditional Rails developers, most of them don't have enough knowledge about current Front End ecosystem, "frontend devs think you are doing ops work, and ops devs think you are doing frontend work". You are in the middle of no where, and without any help.

It's more of an open discussion as I want to hear your opinion on the definition here, and I hope it could help others who have the same question as well. Thanks for reading!

**Comment by gaearon** [comment]
Yeah, I see what you mean. I’m not sure I can really “answer” this so I’ll close, but thanks for writing this up! If you have specific questions let me know :smile:

**Comment by gaearon** [comment]
As for the definition, I’m not sure coming up with any specific definition really helps. At Facebook, we have a “product infrastructure” team that works on improving developer productivity. However they can’t bestow solutions upon anyone. They are more like an agency whose clients are the product teams—if you come up with a library, or a new build workflow, you need to work closely with the product teams to ensure you are solving their problem, and that they actually want this solution.
