### ISSUE TITLE
What are some key open-source projects that are on your radar that you'd like to explore but don't have time to?

### ISSUE THREAD

**Issue by prakhar1989** [gaearon/ama#12]

**Comment by gaearon** [comment]
- Elm
- Cycle.js
- Rust language
- Flow
- React Native
- Rx [modern rewrite](https://github.com/ReactiveX/RxJS)
- Cerebral

**Comment by prakhar1989** [comment]
Nice list. Link to Cerebral please? I'm not sure I've heard of that one before.

**Comment by prakhar1989** [comment]
Is it this - https://github.com/christianalfoni/cerebral?

**Comment by gaearon** [comment]
Yep!
