### ISSUE TITLE
CRA + Monorepo + Lerna + Yarn

### ISSUE THREAD

**Issue by ahmadawais** [gaearon/ama#153]
Hey, Dan! 🙌
I hope you're doing great. First of thanks for all your work on CRA. It's impressive growth is a compliment to your abilities as a software dev and thought-leader.

I am currently reading through the entire code-base of `create-react-app` and figuring out how I should create a similar app for personal use and one for a completely different eco-system. 🤔

While I am able to pick a lot of it just by reading the source-code, I want to do it right, and I can see that you have learned a lot from your experience of building CRA. Also there're a lot of small chunks of code that would be really useful as separate packages (and are not yet). ⚓️

So, if you're in my shoes where would you start in 2018? I know I am actually asking you about the recipe of explaining a boilerplate of another boilerplate to me — but anything I can get from you at this moment would be useful 👍 

Looking forward!
Peace! ✌️

**Comment by gaearon** [comment]
I’d start by forking CRA and then removing everything I don’t need. To be honest I don’t remember a lot of the things we did myself.

Having a set of integration tests ended up pretty important. Other than that, happy to answer more focused questions 🙂

**Comment by ahmadawais** [comment]
@gaearon That's my initial thought. Over the last two weeks I have dug in and read the entire code base of `create-react-app` found a few potential issues as well (nothing big) — that I'll try to send PR's for this year.

That has actually helped a lot. I am close to release what I have build, I'll try and post it here for you to review it whenever you get time for that (and yes, I know, you're a human and you don't scale) 😆 

Thanks a lot for your work on CRA. I haven't had a chance to implement the integration tests but that's what's next.

**Comment by ahmadawais** [comment]
Closing this ticket with the link to what I built in case you want to take a look at it #DanTheMan 👍 

---

## Here's What I Built:

![image](https://camo.githubusercontent.com/fa8908d2c0f59dd82a9c231c68660beaf2f6d929/687474703a2f2f6f6e2e61686d64612e77732f6f7278622f63)

`create-guten-block` → https://github.com/ahmadawais/create-guten-block

🔥 ⚛‏ 📦 A zero-configuration #0CJS developer toolkit for building WordPress Gutenberg block plugins. https://AhmdA.ws/CreateGutenBlock_
