### ISSUE TITLE
What's your most favorite and least favorite thing about St.Petersburg?

### ISSUE THREAD

**Issue by prakhar1989** [gaearon/ama#22]

**Comment by gaearon** [comment]
Favorite thing: local authentic cheap places to have a meal or a drink.
Least favorite thing: it's in Russia.

**Comment by SACRD** [comment]
Обидно.

**Comment by nodkz** [comment]
Я прекрасно понимаю Дена и поддерживаю его. Вся разница в менталитете: у нас сильно любят критиковать и хаить, а за бугром помогают и развивают. У нас гладиаторские бои, а там клуб джентельменов.

PS. Не без исключений конечно, что у нас есть суперские люди, что там есть неадекваты.
PSS. https://soundcloud.com/radiojspodcast/radiojs-28 про русское комьюнити с 40 минуты.
