### ISSUE TITLE
How many people are you really? :P

### ISSUE THREAD

**Issue by ghost** [gaearon/ama#24]
2? 4? 20?

What does your work schedule look like / Do you sleep? What is your trick to getting so much done consistently?

**Comment by gaearon** [comment]
Just one, but see https://github.com/gaearon/ama/issues/4.
The rest of the question I'll answer in https://github.com/gaearon/ama/issues/7.

**Comment by prakhar1989** [comment]
> Just one,

Prove it with a selfie? :stuck_out_tongue_closed_eyes:

**Comment by gaearon** [comment]
Green dots on my face are from antiseptic, I'm recovering from chickenpox :-)

![photo on 9-14-15 at 20 28](https://cloud.githubusercontent.com/assets/810438/9856796/56e545fe-5b1f-11e5-839b-3b8fe25fc563.jpg)

**Comment by prakhar1989** [comment]
Thanks! :D Get well soon!
