### ISSUE TITLE
Do you think Single Page Applicatins (SPAs) will be gone forever and get replaced by react-based frameworks?

### ISSUE THREAD

**Issue by immysl** [gaearon/ama#25]
SPA frameworks such as AngularJS, Ember and backbone are still around. As React-based frameworks have come into prominence, will SPA frameworks be replaced soon?

**Comment by gaearon** [comment]
Isn't React an SPA framework itself? I'm not sure I fully understand the question.

**Comment by ashtonsix** [comment]
MVC web frameworks?

**Comment by immysl** [comment]
Ya MVC. I used the wrong wording. My bad. Anyway React came up with server side rendering before these frameworks started to get that feature. Hence, the confusion.

**Comment by gaearon** [comment]
I'm pretty sure Ember and Angular are here to stay, and will get closer to React's declarative model (in fact that's exactly what's happening now).

I'd like to think that the future frameworks worthy of attention will be **more predictable**. For view layer, it means rendering as a function of state a la React. For model layer, it means immutability, and a single point of mutation (e.g. root state tree with replace function).

**Comment by gryzzly** [comment]
@immysl backbone [rendr](https://github.com/rendrjs/rendr) from AirBNB was announced half a year before React was. I don't like the grumpiness but for the historical context of server sider rendering (which btw was the norm before single page apps appeared) you can take a look at http://blog.getify.com/unimorphic-isoversal-javascript-what/
