### ISSUE TITLE
What's your favorite gif?

### ISSUE THREAD

**Issue by sindresorhus** [gaearon/ama#3]

**Comment by gaearon** [comment]
Anything from [Broad City](http://fuckyeahbroadcity.tumblr.com/).

<table>
<tr>
<td>
<img src='http://38.media.tumblr.com/f0ea37b0e4f73b0a9c61cd41910082ed/tumblr_n0lfxbE07O1qci9uio2_250.gif'>
</td>
<td>
<img src='http://38.media.tumblr.com/76ebbaf269d7b7fa43baa908380af40b/tumblr_n0lfxbE07O1qci9uio1_250.gif'>
</td>
</tr>
<tr>
<td>
<img src='http://31.media.tumblr.com/0a403696edd14fcac282cf63e6e01628/tumblr_n0lfxbE07O1qci9uio10_r1_250.gif'>
</td>
<td>
<img src='http://33.media.tumblr.com/58dd21ea628e0b92b8c0763447aa955d/tumblr_n0lfxbE07O1qci9uio3_250.gif'>
</td>
</tr>
<tr>
<td>
<img src='http://33.media.tumblr.com/2e3aeb00af6895daaaf8c9f6597a472f/tumblr_n0lfxbE07O1qci9uio5_250.gif'>
</td>
<td>
<img src='http://33.media.tumblr.com/f1a5dcfec477791efd429f066183acc8/tumblr_n0lfxbE07O1qci9uio4_250.gif'>
</td>
</tr>
<tr>
<td>
<img src='http://38.media.tumblr.com/257527227dbb7496cbf0a033d7a14612/tumblr_n0lfxbE07O1qci9uio6_250.gif'>
</td>
<td>
<img src='http://38.media.tumblr.com/958c07d73044d5f900dc429fb66f7331/tumblr_n0lfxbE07O1qci9uio7_r1_250.gif'>
</td>
</tr>
<tr>
<td>
<img src='http://38.media.tumblr.com/72c896eb0bab01c3b3b9c835748952d9/tumblr_n0lfxbE07O1qci9uio9_r1_250.gif'>
</td>
<td>
<img src='http://31.media.tumblr.com/93eecb486f0d2fd90ed04f22ff7db774/tumblr_n0lfxbE07O1qci9uio8_r1_250.gif'>
</td>
</tr>
</table>
