### ISSUE TITLE
What is the last technology book you've read?

### ISSUE THREAD

**Issue by eush77** [gaearon/ama#30]

**Comment by gaearon** [comment]
I haven't read books for a very long time, so I don't remember.

I binge-read whole [waitbutwhy](http://waitbutwhy.com) and [Programming in 21th century](http://prog21.dadgum.com/) blogs fairly recently, but I'm not sure if that counts.

I see enough technical stuff during the day, so if I were to read a book, I'd rather prefer it to be about reflections on programming or funny anecdotes a la http://folklore.org/ than heavy technical stuff.
