### ISSUE TITLE
Which recently developed technology do you think will have the most impact 5-10 years from now and why?

### ISSUE THREAD

**Issue by ashtonsix** [gaearon/ama#31]

**Comment by gaearon** [comment]
Excluding React, I think [Elm](http://elm-lang.org/) and [Cycle](http://cycle.js.org) are going to enjoy a tremendous influence because they're applying functional programming in a [user-friendly and mainstream-focused way](http://www.youtube.com/watch?v=oYk8CKH7OhE) to solve real problems.
