### ISSUE TITLE
Your view about Google incremental-dom ?

### ISSUE THREAD

**Issue by asvny** [gaearon/ama#34]

**Comment by gaearon** [comment]
I like to have a tree, and incremental-dom's explicit goal is not to have a tree. Having a tree lets you do things like [react-motion](https://github.com/chenglou/react-motion) or [react-transform-catch-errors](https://github.com/gaearon/react-transform-catch-errors). I don't know how to implement them with incremental-dom.

**Comment by annamalai-saro** [comment]
(y)

**Comment by asvny** [comment]
:+1:
