### ISSUE TITLE
Do you think css-modules is a big deal?

### ISSUE THREAD

**Issue by ghost** [gaearon/ama#36]
for reference: https://github.com/css-modules/css-modules

**Comment by 0xR** [comment]
+1

**Comment by gaearon** [comment]
Yes. If you're not ready to go with inline styles yet for various reasons, I think it's a great improvement over the traditional CSS model, and I'd highly recommend it.

**Comment by nickzarate** [comment]
@gaearon Based on your answer, does that mean you prefer inline styles over css and css modules? If so why?
