### ISSUE TITLE
Why do you not have a full-time job?

### ISSUE THREAD

**Issue by mkazantsev** [gaearon/ama#37]

**Comment by gaearon** [comment]
I used to work full time at [Stampsy](http://stampsy.com/) until April 2015, but they had funding difficulties, and I needed a lot of time to prepare for my React Europe talk and other open source work so I started doing contract work. This way I could focus on my open source more than ever before, practically working on it full time.

After React Europe, I launched a three months [Patreon campaign](http://patreon.com/reactdx) to fund my work. It's been going really well, so I'm able to at least try to [finish my stuff](http://250bpm.com/blog:50) before landing my next full time job around November.

**Comment by mkazantsev** [comment]
Nice, thanks for the answer and good luck with your move to London. I've lived here for 2 years now and don't regret a second I ended up in the UK despite was initially mostly aiming for the US.
