### ISSUE TITLE
What music do you listen to while coding?

### ISSUE THREAD

**Issue by philihp** [gaearon/ama#40]

**Comment by gaearon** [comment]
Airhead
Alice Smith
alt-J
Angel Haze
Aphex Twin
Atoms for Peace
Bat for Lashes
Baths
Beach House
Beck
Bibio
Blue Hawaii
Bon Iver
Broken Bells
Broken Social Scene
Cat Power
Daft Punk
Damon Alburn
Danger Mouse & Sparklehorse
Dirty Projectors
Earl Sweatshirt
Eels
Elliott Smith
FKA Twigs
Four Tet
Gold Panda
Gorillaz
Grandaddy
Hot Chip
Jackson C. Frank
James Blake
Jamie xx
Jeff Lynne
Jessica Pratt
Joni Mitchell
Junip
Kanye West
Kate Tempest
Kendrick Lamar
Lana Del Ray
Mark Kozelek & Jimmy LaValle
Massive Attack
Metronomy
Midlake
Miguel
Moderat
Portugal. The Man
Radiohead
Regina Spektor
Roseaux
Santigold
SBTRKT
Sharon Van Etten
Simon & Garfunkel
SOHN
Sparklehorse
STRFKR
The Strokes
Sufjan Stevens
Sun Kil Moon
Tame Impala
Volcano Choir
The xx
Yeasayer
Yo La Tengo

**Comment by kylejaster** [comment]
yea, this is perfect.
