### ISSUE TITLE
What do you think of the potential of this dev tool for Redux?

### ISSUE THREAD

**Issue by romseguy** [gaearon/ama#41]
![demo...](https://raw.githubusercontent.com/romseguy/redux-store-visualizer/master/demo.gif)

It still needs a few features like searching, panning, and zooming to be usable for large state trees. Also, a dockable component is a suggestion I got and I think it would indeed be nice to have a button in a corner to pop in/out the chart.

So I figured I'd ask your opinion about it since your talk at RE on Redux dev tools inspired me to release this one. What do you think?

[demo code](https://github.com/romseguy/redux-store-visualizer)

**Comment by gaearon** [comment]
I love this! Eager to see more of your experiments!

**Comment by gravitypersists** [comment]
+1 - might suggest color highlighting on node modifications (similar to devtools elements panel on dom modifications!)
