### ISSUE TITLE
Do you have any tips on how to migrate legacy webapps to webpack?

### ISSUE THREAD

**Issue by winterbe** [gaearon/ama#46]
Say, you're working on a mature legacy SPA webapp based primary on jQuery with some newer features already implemented with React. The JavaScript code is structured in old-school modules (and there's a lot of them):

``` js
(function(global) {
  // ...
  global.MyModule = {...};
})(window);
```

Could you describe your approach on how to introduce CommonJS/ ES6/ Webpack modules to such project?

Thanks.

**Comment by gaearon** [comment]
Personally when I had this kind of task, I just walked over tons of modules and manually reformatted them to be in CommonJS. I'd replace some common patterns via "find and replace" but it was mostly manual work.

**Comment by STRML** [comment]
@winterbe See also `exports-loader`, which can fix this kind of issue _and_ prevent the leak to global. If most of your modules follow a similar style, you can apply a loader to all of them and fix the issue in your bundle.

This code will create a local variable called `window` in the module's scope and set it to an empty object so your module is unable to actually export to global. Then, it will add `module.exports = window.MyModule` to the module so you can use it like a proper commonjs module.

`require("imports?window=>{}!exports?window.MyModule!./file.js")`

From http://webpack.github.io/docs/shimming-modules.html

**Comment by winterbe** [comment]
Thanks for pointing that out. I'll give it a shot.
