### ISSUE TITLE
recommendations for using types with redux

### ISSUE THREAD

**Issue by davidjnelson** [gaearon/ama#48]
Hi Dan,

I saw the issue mentioning that babel doesn't work well with flow, and that flow is not on the near term roadmap for redux.  I also saw that some people have been contributing typescript definitions.

Do you have any pointers on how to use types with redux?  This is coming from the perspective of migrating an app that is built with php, jquery, and pjax into react, redux, and immutable.

Thanks,
David

**Comment by gaearon** [comment]
Hey David!

Currently I don't have any tips because I'm not very familiar with this area. There was some work by @leoasis on this in https://github.com/rackt/redux/pull/356, but it's currently outdated and incomplete.

**Comment by leoasis** [comment]
Yeah, I've been trying to continue that work, but I don't have enough time right now. Surely willing to continue discussion in that issue or in a new one in redux though, if someone else is willing to work on it
