### ISSUE TITLE
What's your stand on Relay?

### ISSUE THREAD

**Issue by LorbusChris** [gaearon/ama#51]
...and how do you see it integrating with Redux in the future?

**Comment by yodairish** [comment]
+1

**Comment by gaearon** [comment]
I'm not sure about integration—I currently don't have time resources to investigate that. I know there have been [experiments with binding GraphQL to Redux](https://github.com/gyzerok/adrenaline). You can track and discuss them here: https://github.com/rackt/redux/issues/464. See also this discussion: https://github.com/rackt/redux/issues/775.
