### ISSUE TITLE
What is your take about Etse.js?

### ISSUE THREAD

**Issue by Restuta** [gaearon/ama#52]
In particular interested in this statement:

> Redux aims to be the framework to rule them all. It wants to be everything for everyone, while Este assumes being strongly opinionated, needing much less boilerplate to work. Moreover, while Redux (or many other implementation of the Flux pattern) are frameworks, Este tries to simply be the show a pattern and a set of best practices.

[source](https://github.com/este/este#whats-the-difference-with-redux)

What advantages/disadvantages of Redux do _you_ see over that implementation?

**Comment by gaearon** [comment]
Redux, if you omit sanity checks and comments, is [99 lines and no dependencies](https://gist.github.com/gaearon/ffd88b0e4f00b22c3159).
Is that what we call a framework these days?

I'm not very familiar with Este so I can't really comment on it. I'd just say Redux is a set of contracts and a a few functions to stick them together. Around these contracts, there is an ecosystem of tools. You pick just the tools you need. Some people might want to use Immutable and React Router, some people might use want something simpler or smaller. Redux gives you that choice.

Este, from what I know, is an opinionated stack, more like Rails. Whether you prefer to make your own choices and glue small pieces together, or to have somebody else pick them for you, is really your choice. Both approaches can be great, depending on your requirements, team, time resources, personal preferences, etc.

P.S. [Este uses Redux inside](https://github.com/este/este/blob/master/common/package.json#L20) and I don't see that FAQ entry now. :wink:
