### ISSUE TITLE
What are you thoughts of the elm programming language?

### ISSUE THREAD

**Issue by pruett** [gaearon/ama#54]
You mentioned that you drew inspiration from [Elm](http://elm-lang.org/) when writing Redux. Can you expand on your thoughts of the Elm programming language? Specifically, do you see it as a viable alternative to writing javascript today or maybe sometime in the future? Is the lack of tooling (i.e. webpack, browserify, gulp, etc.) and an established ecosystem like node/npm something that deters you from writing in it?

**Comment by gaearon** [comment]
I think Elm seems amazing. I definitely see it as a viable alternative to JavaScript. I think we're not yet close to where most people would be comfortable with its programming model, but we're slowly getting there.

I'm not very familiar with Elm's tooling but they have their own bundler and package manager, so I'm not sure whether (not) using Webpack/Browserify would even be a problem. All in all, it seems that Evan is paying tremendous attention to the tooling, so I'm not worried about it much.

The only reason I don't dive into Elm is that I'm too lazy to learn a new programming language right now, and I don't have a side project to do in it. I think that learning Elm and ClojureScript is something I'll have to do sooner or later to become a better developer though.

**Comment by pruett** [comment]
:+1: dope
