### ISSUE TITLE
What are your thoughts on using stateless function components + redux as the way to maintain UI state?

### ISSUE THREAD

**Issue by jimbolla** [gaearon/ama#55]
Would you do it? And if so, how would you shape your state to separate UI state from model state?

**Comment by gaearon** [comment]
Tough question. I wouldn't go so far as to put _all_ state into Redux store—just what feels natural and simplifies the surrounding code, predictability and testing.

To be honest I have no idea about the future of managing state. I don't think `setState()` is the right API but I'm not sure about alternatives either. I think we might have gone too far into the [“externalize the state”](https://github.com/facebook/react/issues/4595) direction thus losing the colocation. Maybe React can provide a better state API that would yield the same benefits as Redux gives you, but with colocation.

I'm really interested in “fractal architectures” like Elm Architecture and Cycle's Nested Dialogues as [Andre Staltz describes here](staltz.com/unidirectional-user-interface-architectures.html). I wrote [React Elmish Example](https://github.com/gaearon/react-elmish-example/) to try to better understand Elm architecture myself.

The future is fun and

![12968-i-have-no-idea-what-im-doing1](https://cloud.githubusercontent.com/assets/810438/10269681/aefcf468-6ae6-11e5-9afa-4ea77d199679.jpg)
