### ISSUE TITLE
What is your world view like ?

### ISSUE THREAD

**Issue by emilchacko** [gaearon/ama#57]
how do you look at life ? What are your spiritual views or philosophies ?

**Comment by gaearon** [comment]
I think we are shells for sequences of numbers that encode instructions to produce such shells and have them replicate themselves by getting drugged with chemicals encouraging them to stay alive long enough to produce the next shells before the current ones have fallen apart.

That said the feeling of colors, or listening to a new album, or eating great food, or lying under the sun, or engaging in a conversation with friends is so good, and that my muscle coordinator engine isn't a philosophical zombie is the greatest mystery to me. If there's one thing I hope to learn before I die it's why red feels red and blue feels blue, and I really hope there is an objective and non-reductionist explanation, and that the question even makes sense. Put it another way: if my brain is simulated in a computer and then the entire human race is wiped out and nobody in the universe remembers how computers work, what is it that keeps me running when nobody is able to interpret me as something other than randomly shifting charges on metallic plates?
