### ISSUE TITLE
How do you plan your learning time?

### ISSUE THREAD

**Issue by yodairish** [gaearon/ama#58]
How do you found time to learn new stuff? And what is a process? Did you read docs first or try to do some app like todo or more complicated?
For an example, I really wanna try to learn some fp language(cause in js it's trend and many people tells that is a big step), but I have a full time job and side project at home and also there is tons of stuffs in js(relay for example) which mb I can use in production. In other hand I don't know where and when I can use fp in real projects.. so I just don't know how to take a time to learn it? Did you faced with this problem?

**Comment by gaearon** [comment]
It's a very good question, thanks.

Personally I was always very bad at allocating time for learning. I'm too lazy to follow through with something I plan for myself unless I have a very good reason to do this.

These are three learning approaches that worked for me:
- Quit your job. Save some money to last through a couple of months. During those months, work on a side project using the tools and techniques you want to learn about.
- Find a justification to learn these tools and techniques at your job. Whether or not this can work for you depends on your job. For example, if you generally deliver on time, maybe you can ask your supervisor or manager to allow you to spend a week prototyping some new feature with a different tool or approach.
- If you can't justify diving into new tech right now but you're excited about it, you should at least learn when it's applicable. For example, if you're interested in functional programming, learn when it's beneficial (e.g. untangling complex messy data mutations) and when a task like this comes up at your day job, use it as an excuse to learn more about FP without sacrificing too much time. Generally you want to seize any opportunity where you feel like investing a day of learning can cut the task for more than a day. This way you don't even have to tell anyone anything—you were just doing your job, and learning was a side effect.
