### ISSUE TITLE
How do you think the web will look like in 10 years?

### ISSUE THREAD

**Issue by sindresorhus** [gaearon/ama#6]

**Comment by rusintez** [comment]
:heavy_plus_sign: :one:

**Comment by gaearon** [comment]
This is going to sound really silly in 10 years but here we go.
- NPM will be a great package manager.
- In-browser 3D games will be commonplace.
- JavaScript will get value types.
- Compile-to-JS languages like Elm and ClojureScript will evolve and get better adoption in startups and small product companies, but still won't enjoy mainstream usage.
- JS bundlers like Browserify and Webpack will be a thing of the past. Modules will be transferred efficiently on demand via HTTP2-or-I-don't-really-know-what's-up-in-networking-world-so-I'm-going-to-sound-really-stupid.
- New JavaScript frameworks will be expected to support server rendering.
- Hot reloading becomes commonplace, via different mechanisms (on debugger level like Amok, on code level like React Hot Loader). New frameworks will be expected to support hot reloading at least in some way. If hot reloading becomes an obscure thing that everybody forgot, that would make me incredibly sad.
- Many applications will be written as universal, sharing business logic between web, Android, iOS, etc. The web will still suck for native UIs, so we'll still implement separate views on each platform, but with JavaScript.
- There'll be Bootstrap in WebGL.
