### ISSUE TITLE
What dev tool do you wish existed?

### ISSUE THREAD

**Issue by Widdershin** [gaearon/ama#60]
P.S: I'm the author of [cycle-time-travel](/cyclejs/cycle-time-travel). I was inspired to write it after watching your talk on Hot Reloading with Time Travel. Thank you for creating such cool things and taking the time to share your thoughts :smile:

**Comment by gaearon** [comment]
Inspiring people to write developer tools is exactly what I hoped to do, so I'm very happy!

I wish there existed a tool to let me design components visually in my editor, side by side with code. It would use hot reloading to update the preview as I change the code, and it would let me pick prop sets from real usage sites.
