### ISSUE TITLE
Converting a Backbone.js SPA to React

### ISSUE THREAD

**Issue by chrishoage** [gaearon/ama#64]
If you had to convert a Backbone.js app to use React that was backed by Backbone Models and Collections what would be your approach?

**Comment by gaearon** [comment]
There are solutions like [backbone-redux](https://github.com/redbooth/backbone-redux) that sync models to Redux state. This can be a first step. Gradually I'd replace code operating on Backbone collections and models with code subscribed to the store and firing actions, and eventually, remove Backbone.
