### ISSUE TITLE
What's your favorite Pokémon?

### ISSUE THREAD

**Issue by silvenon** [gaearon/ama#67]

**Comment by gaearon** [comment]
As a kid I really liked Mewtwo.

![mewtwo](https://cloud.githubusercontent.com/assets/810438/11050677/11a4df48-8759-11e5-9c71-267a6088a1cb.png)

Now I prefer Ditto.

![ditto-pokemon-38777727-700-500](https://cloud.githubusercontent.com/assets/810438/11050712/688ee6f0-8759-11e5-971f-a46c922d7d30.jpg)
