### ISSUE TITLE
What work do you do at Facebook?

### ISSUE THREAD

**Issue by yangshun** [gaearon/ama#77]
Saw that you joined Facebook recently and I'm wondering what are your roles and responsibilities there? What work do you do at Facebook besides React?

**Comment by aweary** [comment]
Seconding this question!

**Comment by gaearon** [comment]
After two months of Bootcamp (where I did random things for different teams) I landed in React Core team. I’ll be helping the team make React better in different areas like state management, tooling, etc.

**Comment by aweary** [comment]
Very cool, congrats!
