### ISSUE TITLE
What ST3 plugins you use for ES6? For example, click to jump to file in 'import from' line.

### ISSUE THREAD

**Issue by rifeljm** [gaearon/ama#8]

**Comment by gaearon** [comment]
Besides Spacegray + Oceanic Next themes, Babel language definition and SublimeLinter (#1), I don't use any plugins. I guess I'm too lazy to learn them. I'm also afraid I'll switch to Atom eventually so I don't want to get used to something I'll abandon.

**Comment by damassi** [comment]
I went the Sublime -> Vim -> Atom route and with the latter, was able to take pretty much all of the plusses of the previous two and combine them into a superpower. AND FINALLY be able to design the color / syntax theme I've always wanted. Atom continuously impresses.

**Comment by pavanmehta91** [comment]
@gaearon Are you still using the same plugins? If your setup has upgraded what are the changes? I wanna switch to Sublime from VSCode
