### ISSUE TITLE
Is there vanilla js bindings for redux?

### ISSUE THREAD

**Issue by davej** [gaearon/ama#80]
I've been playing around with Redux and React for the last couple of weeks and now I'm seeing if I can apply some of the patterns/principles to a node backend (just as a learning experiment). I was hoping that there would be a redux helper lib for connecting actions and state with vanilla (no framework) javascript functions (or classes) but I haven't found anything so far?

I might try making my own simple little lib for this but I'm wondering if there's any prior art that I'm missing?

The end user API might look something like below:

``` js
@connect(state => state.todos, todoActions)
export default function Todos({ addTodo, toggleTodo }) {
  // { addTodo, toggleTodo } are todoActions

  return {
    init(todos) {},
    update(todos, oldTodos) {
      // Called when selected state has been changed (shallowEquals)
    }
  }

}
```

Any thoughts on this?

**Comment by gaearon** [comment]
Feel free to make your own! No, I haven’t seen anything like this.

**Comment by davej** [comment]
Thanks. I'm new enough to Redux (and actions/reducers) that I'm still not quite sure if the approach is silly or not.

Does it seem like a reasonable way to do things? No need to go into depth (one word answer is fine) :).

**Comment by gaearon** [comment]
You can do this but it would very much depend on the API you chooses for “components”. If that qualifies as vanilla JS, I guess it’s fine :-)

**Comment by davej** [comment]
:+1: Thanks!

**Comment by davej** [comment]
If anybody stumbles across this... the lib mentioned above is now available at: https://github.com/davej/js-redux :-)

**Comment by veggiemonk** [comment]
@davej nice work!
