### ISSUE TITLE
Redux and GraphQL

### ISSUE THREAD

**Issue by hunterc** [gaearon/ama#87]
Recently started working a redux + GraphQL library. Currently it uses normalizr (thanks by the way) and an introspection query to generate schemas on the fly and a middleware to handle calling GraphQL.

What are your thoughts on Redux in the new Relay, colocated data world?

**Comment by gaearon** [comment]
I think declarative data fetching is the future but I also like having reducers for local updates. I think some mix of those solutions will likely eventually gain popularity, whether it ends up in Relay or other libraries.
