### ISSUE TITLE
Which book which you have read, has changed the way you think about life, universe and everything?

### ISSUE THREAD

**Issue by techyrajeev** [gaearon/ama#89]

**Comment by gaearon** [comment]
[The Beginning of Infinity: Explanations That Transform the World](http://www.amazon.com/The-Beginning-Infinity-Explanations-Transform/dp/0143121359).
Never mind the corny cover, it’s a great book.

**Comment by gaearon** [comment]
If books that I never finished count, [GEB](https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach) too. :smile:

**Comment by techyrajeev** [comment]
Going to buy that "The Beginning of Infinity: Explanations That Transform the World."  :+1:
