### ISSUE TITLE
Does mystery about consciousness led you to explore indic religions such as Buddhism,Hinduism,Taoism ?

### ISSUE THREAD

**Issue by techyrajeev** [gaearon/ama#90]
I saw some of your tweets mention pearl of wisdom from Taoism,Buddha, enlightenment etc. What prompted you to think in that direction? Do you do mediation , yoga to unravel the mystery of consciousness ?

**Comment by gaearon** [comment]
I’ve been interested in religions as a teenager but later became uncomfortable with the explanations they offer and stopped looking there for answers. I do think meditating is cool though as we are way too stressed with too many voices in our heads. However I’m too lazy to do it.
