### ISSUE TITLE
What should a Sr. Javascript Developer know?

### ISSUE THREAD

**Issue by crysislinux** [gaearon/ama#99]
I always find some companies hiring Sr. Javascript Developer.  But what makes a developer senior, products he makes or something else? 

Could I be a Sr. Javascript Developer if I am young(of course, you are young, but that's another question :) )?

**Comment by gaearon** [comment]
I don’t know :smile: . I think people usually just mean some having real world experience building products in the niche you want to work on. Some companies don’t even have a notion of “Sr”.
